// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQtLTPxvMEyofbxAhTNX3wGc-Dc8nODJE',
    appId: '1:629265217898:web:d74754cf2b986cd7b08d13',
    messagingSenderId: '629265217898',
    projectId: 'instagram-clone-project-aries',
    authDomain: 'instagram-clone-project-aries.firebaseapp.com',
    storageBucket: 'instagram-clone-project-aries.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt7J9DwCtLzCAMoRf2vfHw5Bw1e18WHSw',
    appId: '1:629265217898:android:f2c492a7848b2e72b08d13',
    messagingSenderId: '629265217898',
    projectId: 'instagram-clone-project-aries',
    storageBucket: 'instagram-clone-project-aries.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd_duU-IzYNzHVu7doyjqQdRIzC-DTYXA',
    appId: '1:629265217898:ios:465b2d1f189cf529b08d13',
    messagingSenderId: '629265217898',
    projectId: 'instagram-clone-project-aries',
    storageBucket: 'instagram-clone-project-aries.appspot.com',
    iosClientId: '629265217898-fme12ca1t7p0206g76fvbq7c3gigas0v.apps.googleusercontent.com',
    iosBundleId: 'com.ariesvelasquez.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd_duU-IzYNzHVu7doyjqQdRIzC-DTYXA',
    appId: '1:629265217898:ios:465b2d1f189cf529b08d13',
    messagingSenderId: '629265217898',
    projectId: 'instagram-clone-project-aries',
    storageBucket: 'instagram-clone-project-aries.appspot.com',
    iosClientId: '629265217898-fme12ca1t7p0206g76fvbq7c3gigas0v.apps.googleusercontent.com',
    iosBundleId: 'com.ariesvelasquez.instagramClone',
  );
}
